# Generated by Django 2.2.3 on 2019-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads', verbose_name='轮播图')),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='描述')),
                ('url', models.URLField(blank=True, default='#', null=True, verbose_name='连接地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='culture', verbose_name='主图')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '公司文化',
                'verbose_name_plural': '公司文化',
            },
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gamevideo', verbose_name='主图')),
                ('video', models.FileField(upload_to='gamevideo', verbose_name='视频')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '游戏视频',
                'verbose_name_plural': '游戏视频',
            },
        ),
        migrations.CreateModel(
            name='HotGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotgame', verbose_name='主图')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
                ('url', models.URLField(blank=True, default='#', null=True)),
            ],
            options={
                'verbose_name': '热门推荐游戏',
                'verbose_name_plural': '热门推荐游戏',
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='life', verbose_name='主图')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '生活',
                'verbose_name_plural': '生活',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='职位名称')),
                ('type', models.CharField(choices=[(1, '技术'), (1, '策划'), (1, '美术'), (1, '市场'), (1, '运营'), (1, '品测'), (1, '行政')], max_length=20)),
                ('time', models.CharField(max_length=20, verbose_name='工作性质')),
                ('where', models.CharField(max_length=20, verbose_name='工作地点')),
                ('num', models.IntegerField(default=0, verbose_name='招聘人数')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('duty', models.CharField(max_length=500, verbose_name='职责')),
                ('require', models.CharField(max_length=500, verbose_name='任职要求')),
            ],
            options={
                'verbose_name': '岗位表',
                'verbose_name_plural': '岗位表',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recommend', verbose_name='主图')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('qq', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '商务合作',
                'verbose_name_plural': '商务合作',
            },
        ),
    ]
