# Generated by Django 2.2.3 on 2019-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='连接地址'),
        ),
        migrations.AlterField(
            model_name='hotgame',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
