# Generated by Django 2.2.3 on 2019-07-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190716_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='desc',
            field=models.CharField(max_length=250, verbose_name='描述'),
        ),
    ]
