# Generated by Django 2.2.3 on 2019-07-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190716_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='desc',
            field=models.CharField(max_length=250, verbose_name='描述'),
        ),
    ]
