# Generated by Django 2.2.3 on 2019-07-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190716_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='num',
            field=models.IntegerField(default=100, verbose_name='招聘人数'),
        ),
        migrations.AlterField(
            model_name='position',
            name='time',
            field=models.CharField(default='全职', max_length=20, verbose_name='工作性质'),
        ),
        migrations.AlterField(
            model_name='position',
            name='where',
            field=models.CharField(default='郑州', max_length=20, verbose_name='工作地点'),
        ),
    ]
