# Generated by Django 2.2.3 on 2019-07-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190717_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.IntegerField(choices=[(1, '技术'), (2, '策划'), (3, '美术'), (4, '市场'), (5, '运营'), (6, '品测'), (7, '行政')], default=1),
        ),
    ]
